name: Prod build and deployment
on:
  push:
    branches:
      - 'main'
      - 'workflow/test'
jobs:
  BuildSimulation:
    # TODO abort this workflow if the git user triggered it is not the release manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          echo building and packing and app...
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo deploying into Test env
  CheckManager:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is release manager
        run: |
          if [ "${{ github.actor }}" != "release-manager" ]; then
            echo "User is not the release manager. Aborting workflow."
            exit 1
          fi
